== Parsing...
== Elaboration...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat
  ;; test.spectec
  def $t_totalize(3) = 5
  ;; test.spectec
  def $t_totalize(10) = 20

;; test.spectec
def $t_totalize2(nat : nat) : nat
  ;; test.spectec
  def $t_totalize2(1) = 2
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = ($t_totalize(n) + $t_totalize2((n + 10)))

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat}(n, n) = n
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat}(n, n, B_A(n)) = n
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat}(n, m, B_A(m)) = (n + m)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*}(n, [n] ++ n'*{n' <- `n'*`}) = true
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i^n{i <- `i*`}) = n

== IL Validation...
== Running pass ite...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat
  ;; test.spectec
  def $t_totalize(3) = 5
  ;; test.spectec
  def $t_totalize(10) = 20

;; test.spectec
def $t_totalize2(nat : nat) : nat
  ;; test.spectec
  def $t_totalize2(1) = 2
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = ($t_totalize(n) + $t_totalize2((n + 10)))

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat}(n, n) = n
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat}(n, n, B_A(n)) = n
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat}(n, m, B_A(m)) = (n + m)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*}(n, [n] ++ n'*{n' <- `n'*`}) = true
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i^n{i <- `i*`}) = n

== IL Validation after pass ite...
== Running pass let-intro...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat
  ;; test.spectec
  def $t_totalize(3) = 5
  ;; test.spectec
  def $t_totalize(10) = 20

;; test.spectec
def $t_totalize2(nat : nat) : nat
  ;; test.spectec
  def $t_totalize2(1) = 2
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = ($t_totalize(n) + $t_totalize2((n + 10)))

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat}(n, n) = n
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat}(n, n, B_A(n)) = n
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat}(n, m, B_A(m)) = (n + m)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*}(n, [n] ++ n'*{n' <- `n'*`}) = true
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i^n{i <- `i*`}) = n

== IL Validation after pass let-intro...
== Running pass typefamily-removal...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat
  ;; test.spectec
  def $t_totalize(3) = 5
  ;; test.spectec
  def $t_totalize(10) = 20

;; test.spectec
def $t_totalize2(nat : nat) : nat
  ;; test.spectec
  def $t_totalize2(1) = 2
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = ($t_totalize(n) + $t_totalize2((n + 10)))

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat}(n, n) = n
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat}(n, n, B_A(n)) = n
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat}(n, m, B_A(m)) = (n + m)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*}(n, [n] ++ n'*{n' <- `n'*`}) = true
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i^n{i <- `i*`}) = n

== IL Validation after pass typefamily-removal...
== Running pass remove-indexed-types...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat
  ;; test.spectec
  def $t_totalize(3) = 5
  ;; test.spectec
  def $t_totalize(10) = 20

;; test.spectec
def $t_totalize2(nat : nat) : nat
  ;; test.spectec
  def $t_totalize2(1) = 2
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = ($t_totalize(n) + $t_totalize2((n + 10)))

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat}(n, n) = n
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat}(n, n, B_A(n)) = n
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat}(n, m, B_A(m)) = (n + m)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*}(n, [n] ++ n'*{n' <- `n'*`}) = true
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i^n{i <- `i*`}) = n

== IL Validation after pass remove-indexed-types...
== Running pass pattern-simp...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat
  ;; test.spectec
  def $t_totalize(3) = 5
  ;; test.spectec
  def $t_totalize(10) = 20

;; test.spectec
def $t_totalize2(nat : nat) : nat
  ;; test.spectec
  def $t_totalize2(1) = 2
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = ($t_totalize(n) + $t_totalize2((n + 10)))

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat, n#1 : nat}(n, n#1) = n
    -- if (n = n#1)
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat, n#3 : nat, n#2 : nat}(n, n#2, B_A(n#3)) = n
    -- if (n = n#3)
    -- if (n = n#2)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, m#1 : nat}(n, m, B_A(m#1)) = (n + m)
    -- if (m = m#1)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*, n#4 : nat}(n, [n#4] ++ n'*{n' <- `n'*`}) = true
    -- if (n = n#4)
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i*{i <- `i*`}) = n
    -- if (n = |`i*`|)

== IL Validation after pass pattern-simp...
== Running pass totalize...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize(3) = ?(5)
  ;; test.spectec
  def $t_totalize(10) = ?(20)
  def $t_totalize{x0 : nat}(x0) = ?()
    -- otherwise

;; test.spectec
def $t_totalize2(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize2(1) = ?(2)
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = (iter_val#2 + iter_val#1)?{iter_val#2 <- $t_totalize(n), iter_val#1 <- $t_totalize2((n + 10))}

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat, n#1 : nat}(n, n#1) = n
    -- if (n = n#1)
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat, n#3 : nat, n#2 : nat}(n, n#2, B_A(n#3)) = n
    -- if (n = n#3)
    -- if (n = n#2)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, m#1 : nat}(n, m, B_A(m#1)) = (n + m)
    -- if (m = m#1)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*, n#4 : nat}(n, [n#4] ++ n'*{n' <- `n'*`}) = true
    -- if (n = n#4)
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i*{i <- `i*`}) = n
    -- if (n = |`i*`|)

== IL Validation after pass totalize...
== Running pass else...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize(3) = ?(5)
  ;; test.spectec
  def $t_totalize(10) = ?(20)
  def $t_totalize{x0 : nat}(x0) = ?()
    -- otherwise

;; test.spectec
def $t_totalize2(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize2(1) = ?(2)
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = (iter_val#2 + iter_val#1)?{iter_val#2 <- $t_totalize(n), iter_val#1 <- $t_totalize2((n + 10))}

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat, n#1 : nat}(n, n#1) = n
    -- if (n = n#1)
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat, n#3 : nat, n#2 : nat}(n, n#2, B_A(n#3)) = n
    -- if (n = n#3)
    -- if (n = n#2)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, m#1 : nat}(n, m, B_A(m#1)) = (n + m)
    -- if (m = m#1)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*, n#4 : nat}(n, [n#4] ++ n'*{n' <- `n'*`}) = true
    -- if (n = n#4)
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i*{i <- `i*`}) = n
    -- if (n = |`i*`|)

== IL Validation after pass else...
== Running pass else-simplification...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize(3) = ?(5)
  ;; test.spectec
  def $t_totalize(10) = ?(20)
  def $t_totalize{x0 : nat}(x0) = ?()
    -- otherwise

;; test.spectec
def $t_totalize2(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize2(1) = ?(2)
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = (iter_val#2 + iter_val#1)?{iter_val#2 <- $t_totalize(n), iter_val#1 <- $t_totalize2((n + 10))}

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat, n#1 : nat}(n, n#1) = n
    -- if (n = n#1)
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat, n#3 : nat, n#2 : nat}(n, n#2, B_A(n#3)) = n
    -- if (n = n#3)
    -- if (n = n#2)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, m#1 : nat}(n, m, B_A(m#1)) = (n + m)
    -- if (m = m#1)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*, n#4 : nat}(n, [n#4] ++ n'*{n' <- `n'*`}) = true
    -- if (n = n#4)
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i*{i <- `i*`}) = n
    -- if (n = |`i*`|)

== IL Validation after pass else-simplification...
== Running pass uncase-removal...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize(3) = ?(5)
  ;; test.spectec
  def $t_totalize(10) = ?(20)
  def $t_totalize{x0 : nat}(x0) = ?()
    -- otherwise

;; test.spectec
def $t_totalize2(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize2(1) = ?(2)
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = (iter_val#2 + iter_val#1)?{iter_val#2 <- $t_totalize(n), iter_val#1 <- $t_totalize2((n + 10))}

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat, n#1 : nat}(n, n#1) = n
    -- if (n = n#1)
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat, n#3 : nat, n#2 : nat}(n, n#2, B_A(n#3)) = n
    -- if (n = n#3)
    -- if (n = n#2)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, m#1 : nat}(n, m, B_A(m#1)) = (n + m)
    -- if (m = m#1)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*, n#4 : nat}(n, [n#4] ++ n'*{n' <- `n'*`}) = true
    -- if (n = n#4)
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'*{n' <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i*{i <- `i*`}) = n
    -- if (n = |`i*`|)

== IL Validation after pass uncase-removal...
== Running pass sub-expansion...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize(3) = ?(5)
  ;; test.spectec
  def $t_totalize(10) = ?(20)
  def $t_totalize{x0 : nat}(x0) = ?()
    -- otherwise

;; test.spectec
def $t_totalize2(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize2(1) = ?(2)
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = (iter_val#2 + iter_val#1)?{iter_val#2 <- $t_totalize(n), iter_val#1 <- $t_totalize2((n + 10))}

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat, n#1 : nat}(n, n#1) = n
    -- if (n = n#1)
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat, n#3 : nat, n#2 : nat}(n, n#2, B_A(n#3)) = n
    -- if (n = n#3)
    -- if (n = n#2)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, m#1 : nat}(n, m, B_A(m#1)) = (n + m)
    -- if (m = m#1)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*, n#4 : nat}(n, [n#4] ++ n'#1*{n'#1 <- `n'*`}) = true
    -- if (n = n#4)
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'#2*{n'#2 <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i#1*{i#1 <- `i*`}) = n
    -- if (n = |`i*`|)

== IL Validation after pass sub-expansion...
== Running pass sub...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
def $t_totalize(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize(3) = ?(5)
  ;; test.spectec
  def $t_totalize(10) = ?(20)
  def $t_totalize{x0 : nat}(x0) = ?()
    -- otherwise

;; test.spectec
def $t_totalize2(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize2(1) = ?(2)
  ;; test.spectec
  def $t_totalize2{n : nat}(n) = $t_totalize(n)

;; test.spectec
def $t_totalize3(nat : nat) : nat?
  ;; test.spectec
  def $t_totalize3{n : nat}(n) = (iter_val#2 + iter_val#1)?{iter_val#2 <- $t_totalize(n), iter_val#1 <- $t_totalize2((n + 10))}

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
def $t_patsimp(nat : nat, nat : nat) : nat
  ;; test.spectec
  def $t_patsimp{n : nat, n#1 : nat}(n, n#1) = n
    -- if (n = n#1)
  ;; test.spectec
  def $t_patsimp{n : nat, m : nat}(n, m) = (n + m)

;; test.spectec
def $t_patsimp2(nat : nat, nat : nat, A : A) : nat
  ;; test.spectec
  def $t_patsimp2{n : nat, n#3 : nat, n#2 : nat}(n, n#2, B_A(n#3)) = n
    -- if (n = n#3)
    -- if (n = n#2)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, m#1 : nat}(n, m, B_A(m#1)) = (n + m)
    -- if (m = m#1)
  ;; test.spectec
  def $t_patsimp2{n : nat, m : nat, k : nat}(n, m, B_A(k)) = ((n + m) + k)

;; test.spectec
rec {

;; test.spectec:53.1-53.28
def $find(nat : nat, nat*) : bool
  ;; test.spectec:54.1-54.26
  def $find{n : nat}(n, []) = false
  ;; test.spectec:55.1-55.27
  def $find{n : nat, `n'*` : nat*, n#4 : nat}(n, [n#4] ++ n'#1*{n'#1 <- `n'*`}) = true
    -- if (n = n#4)
  ;; test.spectec:56.1-56.38
  def $find{n : nat, n_1 : nat, `n'*` : nat*}(n, [n_1] ++ n'#2*{n'#2 <- `n'*`}) = $find(n, n'*{n' <- `n'*`})
}

;; test.spectec
def $len(int*) : nat
  ;; test.spectec
  def $len{n : nat, `i*` : int*}(i#1*{i#1 <- `i*`}) = n
    -- if (n = |`i*`|)

== IL Validation after pass sub...
== Running pass definition-to-relation...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
relation fun_t_totalize_before_fun_t_totalize_case_2: `%`(nat)
  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%`(10)

  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%`(3)

;; test.spectec
relation fun_t_totalize: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%%`(3, ?(5))

  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%%`(10, ?(20))

  ;; test.spectec
  rule fun_t_totalize_case_2{x0 : nat}:
    `%%`(x0, ?())
    -- ~ fun_t_totalize_before_fun_t_totalize_case_2: `%`(x0)

;; test.spectec
relation fun_t_totalize2: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize2_case_0:
    `%%`(1, ?(2))

  ;; test.spectec
  rule fun_t_totalize2_case_1{n : nat, var_0 : nat?}:
    `%%`(n, var_0)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
relation fun_t_totalize3: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize3_case_0{n : nat, var_1 : nat?, var_0 : nat?}:
    `%%`(n, (iter_val#2 + iter_val#1)?{iter_val#2 <- var_0, iter_val#1 <- var_1})
    -- fun_t_totalize2: `%%`((n + 10), var_1)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
relation fun_t_patsimp: `%%%`(nat, nat, nat)
  ;; test.spectec
  rule fun_t_patsimp_case_0{n : nat, n#1 : nat}:
    `%%%`(n, n#1, n)
    -- if (n = n#1)

  ;; test.spectec
  rule fun_t_patsimp_case_1{n : nat, m : nat}:
    `%%%`(n, m, (n + m))

;; test.spectec
relation fun_t_patsimp2: `%%%%`(nat, nat, A, nat)
  ;; test.spectec
  rule fun_t_patsimp2_case_0{n : nat, n#3 : nat, n#2 : nat}:
    `%%%%`(n, n#2, B_A(n#3), n)
    -- if (n = n#3)
    -- if (n = n#2)

  ;; test.spectec
  rule fun_t_patsimp2_case_1{n : nat, m : nat, m#1 : nat}:
    `%%%%`(n, m, B_A(m#1), (n + m))
    -- if (m = m#1)

  ;; test.spectec
  rule fun_t_patsimp2_case_2{n : nat, m : nat, k : nat}:
    `%%%%`(n, m, B_A(k), ((n + m) + k))

;; test.spectec
rec {

;; test.spectec:53.6-53.11
relation fun_find: `%%%`(nat, nat*, bool)
  ;; test.spectec:53.6-53.11
  rule fun_find_case_0{n : nat}:
    `%%%`(n, [], false)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_1{n : nat, `n'*` : nat*, n#4 : nat}:
    `%%%`(n, [n#4] ++ n'#1*{n'#1 <- `n'*`}, true)
    -- if (n = n#4)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_2{n : nat, n_1 : nat, `n'*` : nat*, var_0 : bool}:
    `%%%`(n, [n_1] ++ n'#2*{n'#2 <- `n'*`}, var_0)
    -- fun_find: `%%%`(n, n'*{n' <- `n'*`}, var_0)
}

;; test.spectec
relation fun_len: `%%`(int*, nat)
  ;; test.spectec
  rule fun_len_case_0{n : nat, `i*` : int*}:
    `%%`(i#1*{i#1 <- `i*`}, n)
    -- if (n = |`i*`|)

== IL Validation after pass definition-to-relation...
== Running pass sideconditions...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
relation fun_t_totalize_before_fun_t_totalize_case_2: `%`(nat)
  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%`(10)

  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%`(3)

;; test.spectec
relation fun_t_totalize: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%%`(3, ?(5))

  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%%`(10, ?(20))

  ;; test.spectec
  rule fun_t_totalize_case_2{x0 : nat}:
    `%%`(x0, ?())
    -- ~ fun_t_totalize_before_fun_t_totalize_case_2: `%`(x0)

;; test.spectec
relation fun_t_totalize2: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize2_case_0:
    `%%`(1, ?(2))

  ;; test.spectec
  rule fun_t_totalize2_case_1{n : nat, var_0 : nat?}:
    `%%`(n, var_0)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
relation fun_t_totalize3: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize3_case_0{n : nat, var_1 : nat?, var_0 : nat?}:
    `%%`(n, (iter_val#2 + iter_val#1)?{iter_val#2 <- var_0, iter_val#1 <- var_1})
    -- fun_t_totalize2: `%%`((n + 10), var_1)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
relation fun_t_patsimp: `%%%`(nat, nat, nat)
  ;; test.spectec
  rule fun_t_patsimp_case_0{n : nat, n#1 : nat}:
    `%%%`(n, n#1, n)
    -- if (n = n#1)

  ;; test.spectec
  rule fun_t_patsimp_case_1{n : nat, m : nat}:
    `%%%`(n, m, (n + m))

;; test.spectec
relation fun_t_patsimp2: `%%%%`(nat, nat, A, nat)
  ;; test.spectec
  rule fun_t_patsimp2_case_0{n : nat, n#3 : nat, n#2 : nat}:
    `%%%%`(n, n#2, B_A(n#3), n)
    -- if (n = n#3)
    -- if (n = n#2)

  ;; test.spectec
  rule fun_t_patsimp2_case_1{n : nat, m : nat, m#1 : nat}:
    `%%%%`(n, m, B_A(m#1), (n + m))
    -- if (m = m#1)

  ;; test.spectec
  rule fun_t_patsimp2_case_2{n : nat, m : nat, k : nat}:
    `%%%%`(n, m, B_A(k), ((n + m) + k))

;; test.spectec
rec {

;; test.spectec:53.6-53.11
relation fun_find: `%%%`(nat, nat*, bool)
  ;; test.spectec:53.6-53.11
  rule fun_find_case_0{n : nat}:
    `%%%`(n, [], false)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_1{n : nat, `n'*` : nat*, n#4 : nat}:
    `%%%`(n, [n#4] ++ n'#1*{n'#1 <- `n'*`}, true)
    -- if (n = n#4)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_2{n : nat, n_1 : nat, `n'*` : nat*, var_0 : bool}:
    `%%%`(n, [n_1] ++ n'#2*{n'#2 <- `n'*`}, var_0)
    -- fun_find: `%%%`(n, n'*{n' <- `n'*`}, var_0)
}

;; test.spectec
relation fun_len: `%%`(int*, nat)
  ;; test.spectec
  rule fun_len_case_0{n : nat, `i*` : int*}:
    `%%`(i#1*{i#1 <- `i*`}, n)
    -- if (n = |`i*`|)

== IL Validation after pass sideconditions...
== Running pass alias-demut...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

;; test.spectec
relation fun_t_totalize_before_fun_t_totalize_case_2: `%`(nat)
  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%`(10)

  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%`(3)

;; test.spectec
relation fun_t_totalize: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%%`(3, ?(5))

  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%%`(10, ?(20))

  ;; test.spectec
  rule fun_t_totalize_case_2{x0 : nat}:
    `%%`(x0, ?())
    -- ~ fun_t_totalize_before_fun_t_totalize_case_2: `%`(x0)

;; test.spectec
relation fun_t_totalize2: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize2_case_0:
    `%%`(1, ?(2))

  ;; test.spectec
  rule fun_t_totalize2_case_1{n : nat, var_0 : nat?}:
    `%%`(n, var_0)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
relation fun_t_totalize3: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize3_case_0{n : nat, var_1 : nat?, var_0 : nat?}:
    `%%`(n, (iter_val#2 + iter_val#1)?{iter_val#2 <- var_0, iter_val#1 <- var_1})
    -- fun_t_totalize2: `%%`((n + 10), var_1)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
relation fun_t_patsimp: `%%%`(nat, nat, nat)
  ;; test.spectec
  rule fun_t_patsimp_case_0{n : nat, n#1 : nat}:
    `%%%`(n, n#1, n)
    -- if (n = n#1)

  ;; test.spectec
  rule fun_t_patsimp_case_1{n : nat, m : nat}:
    `%%%`(n, m, (n + m))

;; test.spectec
relation fun_t_patsimp2: `%%%%`(nat, nat, A, nat)
  ;; test.spectec
  rule fun_t_patsimp2_case_0{n : nat, n#3 : nat, n#2 : nat}:
    `%%%%`(n, n#2, B_A(n#3), n)
    -- if (n = n#3)
    -- if (n = n#2)

  ;; test.spectec
  rule fun_t_patsimp2_case_1{n : nat, m : nat, m#1 : nat}:
    `%%%%`(n, m, B_A(m#1), (n + m))
    -- if (m = m#1)

  ;; test.spectec
  rule fun_t_patsimp2_case_2{n : nat, m : nat, k : nat}:
    `%%%%`(n, m, B_A(k), ((n + m) + k))

;; test.spectec
rec {

;; test.spectec:53.6-53.11
relation fun_find: `%%%`(nat, nat*, bool)
  ;; test.spectec:53.6-53.11
  rule fun_find_case_0{n : nat}:
    `%%%`(n, [], false)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_1{n : nat, `n'*` : nat*, n#4 : nat}:
    `%%%`(n, [n#4] ++ n'#1*{n'#1 <- `n'*`}, true)
    -- if (n = n#4)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_2{n : nat, n_1 : nat, `n'*` : nat*, var_0 : bool}:
    `%%%`(n, [n_1] ++ n'#2*{n'#2 <- `n'*`}, var_0)
    -- fun_find: `%%%`(n, n'*{n' <- `n'*`}, var_0)
}

;; test.spectec
relation fun_len: `%%`(int*, nat)
  ;; test.spectec
  rule fun_len_case_0{n : nat, `i*` : int*}:
    `%%`(i#1*{i#1 <- `i*`}, n)
    -- if (n = |`i*`|)

== IL Validation after pass alias-demut...
== Running pass improve-ids...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule mk_TestNestedIter{n_lst_lst_lst : nat***, m_lst_lst : nat**}:
    `%|-%`(n_lst_lst_lst, m_lst_lst)
    -- if (|m_lst_lst| = |n_lst_lst_lst|)
    -- (if (|m_lst| = |n_lst_lst|))+{m_lst <- m_lst_lst, n_lst_lst <- n_lst_lst_lst}
    -- (if (|n_lst| = m))*{m <- m_lst, n_lst <- n_lst_lst}+{m_lst <- m_lst_lst, n_lst_lst <- n_lst_lst_lst}

;; test.spectec
relation fun_t_totalize_before_fun_t_totalize_case_2: `%`(nat)
  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%`(10)

  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%`(3)

;; test.spectec
relation fun_t_totalize: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize_case_0:
    `%%`(3, ?(5))

  ;; test.spectec
  rule fun_t_totalize_case_1:
    `%%`(10, ?(20))

  ;; test.spectec
  rule fun_t_totalize_case_2{x0 : nat}:
    `%%`(x0, ?())
    -- ~ fun_t_totalize_before_fun_t_totalize_case_2: `%`(x0)

;; test.spectec
relation fun_t_totalize2: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize2_case_0:
    `%%`(1, ?(2))

  ;; test.spectec
  rule fun_t_totalize2_case_1{n : nat, var_0 : nat?}:
    `%%`(n, var_0)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
relation fun_t_totalize3: `%%`(nat, nat?)
  ;; test.spectec
  rule fun_t_totalize3_case_0{n : nat, var_1 : nat?, var_0 : nat?}:
    `%%`(n, (iter_val_2 + iter_val_1)?{iter_val_2 <- var_0, iter_val_1 <- var_1})
    -- fun_t_totalize2: `%%`((n + 10), var_1)
    -- fun_t_totalize: `%%`(n, var_0)

;; test.spectec
syntax A = 
  | B(nat)

;; test.spectec
relation fun_t_patsimp: `%%%`(nat, nat, nat)
  ;; test.spectec
  rule fun_t_patsimp_case_0{n : nat, n_1 : nat}:
    `%%%`(n, n_1, n)
    -- if (n = n_1)

  ;; test.spectec
  rule fun_t_patsimp_case_1{n : nat, m : nat}:
    `%%%`(n, m, (n + m))

;; test.spectec
relation fun_t_patsimp2: `%%%%`(nat, nat, A, nat)
  ;; test.spectec
  rule fun_t_patsimp2_case_0{n : nat, n_3 : nat, n_2 : nat}:
    `%%%%`(n, n_2, B_A(n_3), n)
    -- if (n = n_3)
    -- if (n = n_2)

  ;; test.spectec
  rule fun_t_patsimp2_case_1{n : nat, m : nat, m_1 : nat}:
    `%%%%`(n, m, B_A(m_1), (n + m))
    -- if (m = m_1)

  ;; test.spectec
  rule fun_t_patsimp2_case_2{n : nat, m : nat, k : nat}:
    `%%%%`(n, m, B_A(k), ((n + m) + k))

;; test.spectec
rec {

;; test.spectec:53.6-53.11
relation fun_find: `%%%`(nat, nat*, bool)
  ;; test.spectec:53.6-53.11
  rule fun_find_case_0{n : nat}:
    `%%%`(n, [], false)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_1{n : nat, n'_lst : nat*, n_4 : nat}:
    `%%%`(n, [n_4] ++ n'_lst, true)
    -- if (n = n_4)

  ;; test.spectec:53.6-53.11
  rule fun_find_case_2{n : nat, n_1 : nat, n'_lst : nat*, var_0 : bool}:
    `%%%`(n, [n_1] ++ n'_lst, var_0)
    -- fun_find: `%%%`(n, n'_lst, var_0)
}

;; test.spectec
relation fun_len: `%%`(int*, nat)
  ;; test.spectec
  rule fun_len_case_0{n : nat, i_lst : int*}:
    `%%`(i_lst, n)
    -- if (n = |i_lst|)

== IL Validation after pass improve-ids...
== Complete.
